import pyvisa
import time
rm = pyvisa.ResourceManager('@py')
print(rm.list_resources())
samd21 = rm.open_resource('USB0::51966::16384::123456::0::INSTR')
print(samd21.query("*IDN?"))
print("RELAY1:EN value is {}".format(samd21.query("RELAY1:EN?")))
print("RELAY2:EN value is {}".format(samd21.query("RELAY2:EN?")))
time.sleep(1)
samd21.write("RELAY1:EN 1")
print("RELAY1:EN value is {}".format(samd21.query("RELAY1:EN?")))
print("RELAY2:EN value is {}".format(samd21.query("RELAY2:EN?")))
time.sleep(1)
samd21.write("RELAY2:EN 1")
print("RELAY1:EN value is {}".format(samd21.query("RELAY1:EN?")))
print("RELAY2:EN value is {}".format(samd21.query("RELAY2:EN?")))
time.sleep(1)
samd21.write("*RST")
print("RELAY1:EN value is {}".format(samd21.query("RELAY1:EN?")))
print("RELAY2:EN value is {}".format(samd21.query("RELAY2:EN?")))
