import pyvisa
import time
rm = pyvisa.ResourceManager('@py')
print(rm.list_resources())
samd21 = rm.open_resource('USB0::51966::16384::123456::0::INSTR')
print(samd21.query("*IDN?"))
print("GPIO1:RELAY value is {}".format(samd21.query("GPIO1:RELAY?")))
print("GPIO2:RELAY value is {}".format(samd21.query("GPIO2:RELAY?")))
time.sleep(1)
samd21.write("GPIO1:RELAY 1")
print("GPIO1:RELAY value is {}".format(samd21.query("GPIO1:RELAY?")))
print("GPIO2:RELAY value is {}".format(samd21.query("GPIO2:RELAY?")))
time.sleep(1)
samd21.write("GPIO2:RELAY 1")
print("GPIO1:RELAY value is {}".format(samd21.query("GPIO1:RELAY?")))
print("GPIO2:RELAY value is {}".format(samd21.query("GPIO2:RELAY?")))
time.sleep(1)
samd21.write("*RST")
print("GPIO1:RELAY value is {}".format(samd21.query("GPIO1:RELAY?")))
print("GPIO2:RELAY value is {}".format(samd21.query("GPIO2:RELAY?")))
